# 项目基础配置
project:
  name: "Claude AI协作平台"
  version: "1.2.0"
  description: "基于Claude AI的智能代码协作和项目管理平台"
  owner: "AI研发部"
  start_date: "2024-01-15"
  expected_release: "2024-06-30"

# 服务配置
services:
  api:
    base_url: "https://api.claude-collab.com"
    version: "v1"
    timeout: 30
    rate_limit: 1000
    
  database:
    host: "db.claude-collab.com"
    port: 5432
    name: "claude_production"
    user: "claude_user"
    max_connections: 100
    
  cache:
    enabled: true
    ttl: 3600
    type: "redis"

# 功能开关
features:
  code_collaboration: true
  realtime_chat: true
  file_sharing: true
  analytics_dashboard: true
  mobile_app: false
  third_party_integration: false
  advanced_permissions: false

# 监控配置
monitoring:
  enabled: true
  metrics:
    - response_time
    - error_rate
    - user_activity
    - system_health
  alerting:
    enabled: true
    channels:
      - email
      - slack
      - webhook

# 部署配置
deployment:
  environment: "production"
  region: "us-west-1"
  instances: 3
  auto_scaling:
    enabled: true
    min_instances: 2
    max_instances: 10